logging:
  level:
    web: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
    generator:
      IGNORE_UNKNOWN: true
    time-zone: America/Sao_Paulo
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/toolschallenge-h2-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop